# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' add two real numbers
#'
#' This function takes two real numbers and returns their sum
#'
#' @param x a real number
#' @param y a real number
#' @export
#' @return the sume of x and y
NULL

scalarMultiplication <- function(c, M) {
    .Call('_glmnetRcpp_scalarMultiplication', PACKAGE = 'glmnetRcpp', c, M)
}

addReals <- function(x, y) {
    .Call('_glmnetRcpp_addReals', PACKAGE = 'glmnetRcpp', x, y)
}

fitGlmFixed <- function(predictor_matrix, response_vector, alpha = 1, num_lambda = 100L, glm_type = 1L, max_iter = 100L, abs_tol = 1.0e-4, rel_tol = 1.0e-2, normalize_grad = FALSE, k_fold = 5L) {
    .Call('_glmnetRcpp_fitGlmFixed', PACKAGE = 'glmnetRcpp', predictor_matrix, response_vector, alpha, num_lambda, glm_type, max_iter, abs_tol, rel_tol, normalize_grad, k_fold)
}

fitGlmCv <- function(predictor_matrix, response_vector, alpha = 1, num_lambda = 100L, glm_type = 1L, max_iter = 100L, abs_tol = 1.0e-4, rel_tol = 1.0e-2, normalize_grad = FALSE, k_fold = 5L) {
    .Call('_glmnetRcpp_fitGlmCv', PACKAGE = 'glmnetRcpp', predictor_matrix, response_vector, alpha, num_lambda, glm_type, max_iter, abs_tol, rel_tol, normalize_grad, k_fold)
}

ExpNegativeLogLikelihood_cpp <- function(x, predictor_matrix, response_vector, alpha = 1, num_lambda = 100L, glm_type = 1L, max_iter = 100L, abs_tol = 1.0e-4, rel_tol = 1.0e-2, normalize_grad = FALSE, k_fold = 5L) {
    .Call('_glmnetRcpp_ExpNegativeLogLikelihood_cpp', PACKAGE = 'glmnetRcpp', x, predictor_matrix, response_vector, alpha, num_lambda, glm_type, max_iter, abs_tol, rel_tol, normalize_grad, k_fold)
}

GradExpNegativeLogLikelihood_cpp <- function(x, predictor_matrix, response_vector, alpha = 1, num_lambda = 100L, glm_type = 1L, max_iter = 100L, abs_tol = 1.0e-4, rel_tol = 1.0e-2, normalize_grad = FALSE, k_fold = 5L) {
    .Call('_glmnetRcpp_GradExpNegativeLogLikelihood_cpp', PACKAGE = 'glmnetRcpp', x, predictor_matrix, response_vector, alpha, num_lambda, glm_type, max_iter, abs_tol, rel_tol, normalize_grad, k_fold)
}

ProxGradDescent_cpp <- function(predictor_matrix, response_vector, lambda = 0, alpha = 1, glm_type = 1L, max_iter = 100L, abs_tol = 1.0e-4, rel_tol = 1.0e-2, normalize_grad = FALSE, k_fold = 5L) {
    .Call('_glmnetRcpp_ProxGradDescent_cpp', PACKAGE = 'glmnetRcpp', predictor_matrix, response_vector, lambda, alpha, glm_type, max_iter, abs_tol, rel_tol, normalize_grad, k_fold)
}

